from extractors import (
    age,
    appropriate_hormone_use,
    assessment_results_with_diagnoses,
    behavioral_health_remission_months,
    breast_cancer_risk_assessed,
    capacity_for_informed_decision,
    clinical_rationale_for_surgery,
    clinical_relationship_duration_described,
    clinician_available_for_coordination,
    clinician_credentials_from_licensing_board,
    clinician_experience_in_gender_dysphoria,
    clinician_interdisciplinary_engagement,
    clinician_masters_degree_or_above,
    clinician_part_of_gender_team,
    clinician_qualified_competencies,
    comorbid_conditions_assessed,
    comprehensive_assessment_completed,
    diagnosed_gender_dysphoria,
    diagnostic_assessment_included,
    emotional_cognitive_maturity_for_consent,
    favorable_psychosocial_behavioral_eval,
    gender_dysphoria_marked_and_sustained,
    gender_identifying_characteristics_described,
    hormone_duration_months,
    hormones_not_desired_or_contraindicated,
    informed_consent_obtained,
    irreversibility_acknowledged,
    medical_management_compliance,
    meets_recognized_clinical_criteria,
    months_living_as_identified_gender,
    multidisciplinary_team_involved,
    nicotine_free_or_abstained,
    no_medical_contraindications,
    other_causes_excluded,
    parental_or_guardian_consent,
    plan_for_follow_up,
    psychotherapy_duration_months,
    second_independent_clinician_letter,
    significant_concerns_well_controlled,
    social_transition_or_unnecessary,
    surgery_type,
    understands_reproductive_effects,
    understands_risks,
    unequivocal_support_for_procedure,
)

FIELD_REGISTRY = {
    "age": age,
    "appropriate_hormone_use": appropriate_hormone_use,
    "assessment_results_with_diagnoses": assessment_results_with_diagnoses,
    "behavioral_health_remission_months": behavioral_health_remission_months,
    "breast_cancer_risk_assessed": breast_cancer_risk_assessed,
    "capacity_for_informed_decision": capacity_for_informed_decision,
    "clinical_rationale_for_surgery": clinical_rationale_for_surgery,
    "clinical_relationship_duration_described": clinical_relationship_duration_described,
    "clinician_available_for_coordination": clinician_available_for_coordination,
    "clinician_credentials_from_licensing_board": clinician_credentials_from_licensing_board,
    "clinician_experience_in_gender_dysphoria": clinician_experience_in_gender_dysphoria,
    "clinician_interdisciplinary_engagement": clinician_interdisciplinary_engagement,
    "clinician_masters_degree_or_above": clinician_masters_degree_or_above,
    "clinician_part_of_gender_team": clinician_part_of_gender_team,
    "clinician_qualified_competencies": clinician_qualified_competencies,
    "comorbid_conditions_assessed": comorbid_conditions_assessed,
    "comprehensive_assessment_completed": comprehensive_assessment_completed,
    "diagnosed_gender_dysphoria": diagnosed_gender_dysphoria,
    "diagnostic_assessment_included": diagnostic_assessment_included,
    "emotional_cognitive_maturity_for_consent": emotional_cognitive_maturity_for_consent,
    "favorable_psychosocial_behavioral_eval": favorable_psychosocial_behavioral_eval,
    "gender_dysphoria_marked_and_sustained": gender_dysphoria_marked_and_sustained,
    "gender_identifying_characteristics_described": gender_identifying_characteristics_described,
    "hormone_duration_months": hormone_duration_months,
    "hormones_not_desired_or_contraindicated": hormones_not_desired_or_contraindicated,
    "informed_consent_obtained": informed_consent_obtained,
    "irreversibility_acknowledged": irreversibility_acknowledged,
    "medical_management_compliance": medical_management_compliance,
    "meets_recognized_clinical_criteria": meets_recognized_clinical_criteria,
    "months_living_as_identified_gender": months_living_as_identified_gender,
    "multidisciplinary_team_involved": multidisciplinary_team_involved,
    "nicotine_free_or_abstained": nicotine_free_or_abstained,
    "no_medical_contraindications": no_medical_contraindications,
    "other_causes_excluded": other_causes_excluded,
    "parental_or_guardian_consent": parental_or_guardian_consent,
    "plan_for_follow_up": plan_for_follow_up,
    "psychotherapy_duration_months": psychotherapy_duration_months,
    "second_independent_clinician_letter": second_independent_clinician_letter,
    "significant_concerns_well_controlled": significant_concerns_well_controlled,
    "social_transition_or_unnecessary": social_transition_or_unnecessary,
    "surgery_type": surgery_type,
    "understands_reproductive_effects": understands_reproductive_effects,
    "understands_risks": understands_risks,
    "unequivocal_support_for_procedure": unequivocal_support_for_procedure,
}

FIELD_EXCEPTIONS = ["behavioral_health_remission_months", "hormone_duration_months", "months_living_as_identified_gender",
"psychotherapy_duration_months", "clinical_relationship_duration_described", "favorable_psychosocial_behavioral_eval",
"understands_reproductive_effects"
]